theme = "air"
baseurl = "http://example.org/"
title = "Air - Free Website Template, Free HTML5 Template by freehtml5.co"
languageCode = "en-us"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.main]]
    name = "Signup"
    url = "/signup/"
    weight = 5
    button = "true"



[params]
    [params.brand]
        name = "Air"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."

    [params.address]
        street1 = "198 West 21st Street"
        street2 = "Suite 721"
        city = "New York"
        state = "NY"
        zipcode = "10016"

    [params.contact]
        phone = "1234567890"
        email = "info@yoursite.com"
        website = "freehtml5.co"

    [params.footer]
        title = "Hire Us!"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."
        button_text = "Contact Us"
        button_href = "/contact"

    [params.copyright_statement]
        english = "All Rights Reserved."
