theme = "air"
baseurl = "http://example.org/"
title = "Air - Free Website Template, Free HTML5 Template by freehtml5.co"
languageCode = "en-us"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Sign Up"
    url = "/signup/"
    weight = 3

[params]
    [params.title]
        title = "Creativity Is A Wild Mind & A Disciplined Eye"
        subtitle = "Free html5 templates Made by freehtml5.co"
        button_text = "View Demo"
        button_href = "signup"

    [[params.feature.item]]
        icon_name = "hotairballoon"
        title = "Marketing"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "search"
        title = "Search Engine"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "wallet"
        title = "Earn Money"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "wine"
        title = "Entrepreneur"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "genius"
        title = "Strategic Plan"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "chat"
        title = "Support"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."


    [params.wireframe]

    [params.contact_form]
        email_placeholder_text = "Email"
        message_placeholder_text = "Message"
        submit_button_text = "Send Message"

    # Brand configuration.
    [params.brand]
        name = "Air"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."

    [params.address]
        street1 = "198 West 21st Street"
        street2 = "Suite 721"
        city = "New York"
        state = "NY"
        zipcode = "10016"

    [params.contact]
        phone = "1234567890"
        email = "info@yoursite.com"
        website = "freehtml5.co"

    [params.footer]
        title = "Hire Us!"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."
        button_text = "Contact Us"
        button_href = "/contact"

    [params.copyright_statement]
        english = "All Rights Reserved."
